import logging
import asyncio

from fastapi import HTTPException
from tortoise import Tortoise, connections
from tortoise.exceptions import DBConnectionError

from config.settings import TORTOISE_ORM_CONFIG

logger = logging.getLogger("root")


async def init_db(db_config=TORTOISE_ORM_CONFIG):
    try:
        print('db initiated')
        await Tortoise.init(config=db_config)
        await Tortoise.generate_schemas()
        logger.info("‚úÖ Tortoise ORM initialized")
    except DBConnectionError as e:
        logger.error(f"‚ùå Database connection failed: {e}")
        await reconnect_db()


async def close_db():
    await Tortoise.close_connections()
    logger.info("üîå Database connections closed")


async def reconnect_db(retries=5, delay=5):
    for attempt in range(1, retries + 1):
        try:
            await close_db()
            await init_db()
            logger.info("üîÑ Reconnected to DB")
            break
        except Exception as e:
            logger.error(f"‚ö†Ô∏è Retry {attempt}/{retries} failed: {e}")
            await asyncio.sleep(delay)
    else:
        logger.critical("üíÄ Could not reconnect to DB after retries")
        raise HTTPException(status_code=500, detail="Failed to reconnect to the database")
